B-Rock/B-Rock/Controllers/AboutController.cs
using B_Rock.Data;
using B_Rock.Models.About;
using B_Rock.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace B_Rock.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class AboutController : Controller
    {
        private readonly IArtistService _artistService;
        private readonly IInstrumentService _instrumentService;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostEnvironment;
        public AboutController(IArtistService artistService, IInstrumentService instrumentService, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostEnvironment)
        {
            _artistService = artistService;
            _instrumentService = instrumentService;
            _hostEnvironment = hostEnvironment;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            GetAllDevidedInGroup ArtistsInGroup = new GetAllDevidedInGroup();
            for (int i = 1; i <= _instrumentService.GetAmountInstruments(); i++)
            {
                ArtistsInGroup.artistsInGroups.Add(_artistService.GetByInstrument(i).ToList());
            }
            return View(ArtistsInGroup);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(int id)
        {
            Artist deleteArtist = _artistService.GetById(id);
            deleteArtist.IsDeleted = true;
            _artistService.DeleteArtist(deleteArtist);
            return RedirectToAction("Index");
        }
        public IActionResult AddArtist()
        {
            AddArtistViewModel viewModel = new AddArtistViewModel() { Instruments = _instrumentService.GetAll() };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddArtist(AddArtistViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Artist newArtist = new Artist()
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Role = viewModel.Role,
                    InstrumentId = viewModel.InstrumentId,
                    Instrument = _instrumentService.GetById(viewModel.InstrumentId)
                };
                if (viewModel.Image != null)
                {
                    string uniqueFileName = GetUniqueFileName(viewModel.Image.FileName);
                    string uploads = Path.Combine(_hostEnvironment.WebRootPath, "img/Artiesten");
                    string filePath = Path.Combine(uploads, uniqueFileName);
                    viewModel.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    newArtist.UniqueURL = uniqueFileName;
                }
                _artistService.AddArtist(newArtist);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        public IActionResult EditArtist(int id)
        {
            Artist a = _artistService.GetById(id);
            EditArtistViewModel viewModel = new EditArtistViewModel()
            {
                Instruments = _instrumentService.GetAll(),
                Id = a.Id,
                FirstName = a.FirstName,
                LastName = a.LastName,
                Role = a.Role,
                InstrumentId = a.InstrumentId,
                UniqueURL = a.UniqueURL
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditArtist(EditArtistViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Artist editedArtist = new Artist()
                {
                    Id = viewModel.Id,
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Role = viewModel.Role,
                    InstrumentId = viewModel.InstrumentId,
                    Instrument = _instrumentService.GetById(viewModel.InstrumentId),
                    UniqueURL = viewModel.UniqueURL
                };
                if (viewModel.Image != null)
                {
                    string uniqueFileName = GetUniqueFileName(viewModel.Image.FileName);
                    string uploads = Path.Combine(_hostEnvironment.WebRootPath, "img/Artiesten");
                    string filePath = Path.Combine(uploads, uniqueFileName);
                    viewModel.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    editedArtist.UniqueURL = uniqueFileName;
                }
                _artistService.UpdateArtist(editedArtist);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }
        //https://stackoverflow.com/questions/35379309/how-to-upload-files-in-asp-net-core/35385472#35385472
    }
}

B-Rock/B-Rock/Controllers/ContactController.cs
using B_Rock.Data;
using B_Rock.Models.Contact;
using B_Rock.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace B_Rock.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class ContactController : Controller
    {
        private readonly UserManager<B_RockUser> _userManager;
        private readonly IStaffService _staffService;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostEnvironment;
        private readonly IQuestionService _questionService;
        public ContactController(IStaffService staffService, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostEnvironment, UserManager<B_RockUser> userManager, IQuestionService questionService)
        {
            _staffService = staffService;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
            _questionService = questionService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Staff> crew = _staffService.GetAll();
            IndexViewModel viewModel = new IndexViewModel()
            {
                StaffMembers = crew
            };
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                B_RockUser user = await _userManager.GetUserAsync(HttpContext.User);
                viewModel.UserId = user.Id;
                viewModel.FirstName = user.FirstName;
                viewModel.LastName = user.LastName;
                viewModel.Email = user.Email;
            }
            return View(viewModel);
        }
        public IActionResult AddStaff()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Successful()
        {
            return View();
        }
        public IActionResult EditStaff(int Id)
        {
            Staff f = _staffService.GetById(Id);
            EditStaffViewModel viewModel = new EditStaffViewModel()
            {
                Id = f.Id,
                FirstName = f.FirstName,
                LastName = f.LastName,
                PhoneNumber = f.PhoneNumber,
                Email = f.Email,
                UniqueURL = f.UniqueURL,
                Role = f.Role
            };
            return View(viewModel);
        }
        public IActionResult DeleteStaff(int Id)
        {
            Staff deleteStaff = _staffService.GetById(Id);
            DeleteStaffViewModel viewModel = new DeleteStaffViewModel()
            {
                Id = deleteStaff.Id,
                FirstName = deleteStaff.FirstName,
                LastName = deleteStaff.LastName,
                Role = deleteStaff.Role,
                UniqueURL = deleteStaff.UniqueURL
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Index(IndexViewModel viewModel)
        {
            ModelState.Remove("StaffMembers");
            if (ModelState.IsValid)
            {
                Question q = new Question()
                {
                    Email = viewModel.Email,
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Message = viewModel.Message,
                    Created = DateTime.Now
                };
                if (HttpContext.User.Identity.IsAuthenticated) q.UserId = viewModel.UserId;
                _questionService.AddQuestion(q);
                return RedirectToAction("Successful");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStaff(AddStaffViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Staff newStaff = new Staff()
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Role = viewModel.Role,
                    PhoneNumber = viewModel.PhoneNumber,
                    Email = viewModel.Email
                };
                if (viewModel.Image != null)
                {
                    string uniqueFileName = GetUniqueFileName(viewModel.Image.FileName);
                    string uploads = Path.Combine(_hostEnvironment.WebRootPath, "img/Staff");
                    string filePath = Path.Combine(uploads, uniqueFileName);
                    viewModel.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    newStaff.UniqueURL = uniqueFileName;
                }
                _staffService.Add(newStaff);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditStaff(EditStaffViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Staff editStaf = new Staff()
                {
                    Id = viewModel.Id,
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Role = viewModel.Role,
                    PhoneNumber = viewModel.PhoneNumber,
                    Email = viewModel.Email,
                    UniqueURL = viewModel.UniqueURL
                };
                if (viewModel.Image != null)
                {
                    string uniqueFileName = GetUniqueFileName(viewModel.Image.FileName);
                    string uploads = Path.Combine(_hostEnvironment.WebRootPath, "img/Staff");
                    string filePath = Path.Combine(uploads, uniqueFileName);
                    viewModel.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    editStaf.UniqueURL = uniqueFileName;
                }
                _staffService.Update(editStaf);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteStaff(DeleteStaffViewModel viewModel)
        {
            Staff toDelete = _staffService.GetById(viewModel.Id);
            toDelete.IsDeleted= true;
            _staffService.Delete(toDelete);
            return RedirectToAction("Index");
        }
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }
        //https://stackoverflow.com/questions/35379309/how-to-upload-files-in-asp-net-core/35385472#35385472
    }
}

B-Rock/B-Rock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B-Rock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/B_Rock.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo_b'rock.png" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: lightgray">
        <div class="d-flex justify-content-center">
            <div class="footer_informatie">
                <p class="font-weight-bold"><b>Contact</b></p>
                <p>Contact us: <br> <a href="tel:+3293358797">+32 9 335 87 97</a></p>
            </div>
            <div class="footer_informatie">
                <p class="font-weight-bold"><b>Credits</b></p>
                <p>
                    Pictures: Anne Van Aerschot, Davy De Pauw, Mirjam Devriendt, Marco Borggreve, Molina Visuals, Masha
                    Mosconi, Frederik Sadones
                </p>
                <p>Website: Mylan Coudeville</p>
                <p>© B'Rock Orchestra</p>
            </div>
            <div class="footer_informatie">
                <p class="font-weight-bold"><b>Sponsors</b></p>
                <p>B'Rock is supported by:</p>
                <img class="footer_sponser" src="~/img/Vlaanderen.png" alt="Logo Vlaanderen">
                <img class="footer_sponser" src="~/img/Nationale-Loterij.png" alt="Logo Nationale Loterij">
                <img class="footer_sponser" src="~/img/Stad-Gent.png" alt="Logo stad Gent">
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>